on:
  push:
    branches: [main]
  pull_request:

jobs:
  Update_Readme:
  #Create/update Readme.md
    name: Update Readme.md
    runs-on: ubuntu-latest

    # Needed to give the job permission
    # to push to the repository.
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Update README.md
      uses: abhinav/stitchmd-action@fea871cb92ec395350cd06a5e07fe3b43de1d7b4
      with:
        mode: write
        offset: -1
        summary: Readme_Summary.md
        output: README.md
    - uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0
      with:
        branch: main
        file_pattern: README.md
        commit_message: 'Auto-update README.md with stitchmd'
